<a href="https://colab.research.google.com/github/Priyanka-Police-Reddy-Gari/Tensors/blob/main/Priyanka_Using_Tensors_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import time

# <font color = dodgerred>**Create Tensor**
 Creating a torch Tensor of shape (5, 3) which is filled with zeros. Modifying
 the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

In [ ]:
my_tensor = torch.zeros(5,3)

In [ ]:
my_tensor.shape

torch.Size([5, 3])

In [ ]:
my_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Manually set the value at the first row and third column to 10,
# and the value at the third row and first column to 100 in the tensor named "my_tensor".

my_tensor[0][2] = 10
my_tensor[2][0] = 100


In [ ]:
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

# <font color = dodgerred>**Reshape tensor**
We have following tensor as input:

```x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])```

Using only reshaping functions (like view, reshape, transpose, permute), We need to get at the following tensor as output:

```
tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])
```



In [ ]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
x = x.view(6,4).permute(1,0)
x

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# <font color = dodgerred>**Slice tensor**

- Slicing the tensor x to get the following
>- last row of x
>- fourth column of x
>- first three rows and first two columns - the shape of subtensor should be (3,2)
>- odd valued rows and columns

In [ ]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  8, 10],
        [11, 12, 13, 14, 15]])

In [ ]:
x.shape

torch.Size([3, 5])

In [ ]:
# Retrieve the last row of the tensor 'x'
# Hint: Negative indexing can help you select rows or columns counting from the end of the tensor.
# Think about how you can select all columns for the desired row.
last_row = x[-1]
last_row

tensor([11, 12, 13, 14, 15])

In [ ]:
# Retrieve the fourth column of the tensor 'x'
# Hint: Pay attention to the indexing for both rows and columns.
# Remember that indexing in Python starts from zero.
fourth_column = x[:,3]
fourth_column

tensor([ 4,  8, 14])

In [ ]:
# Retrieve the first 3 rows and first 2 columns from the tensor 'x'.
# Hint: Use slicing to extract the required subset of rows and columns.
first_3_rows_2_columns = x[:3,:2]
first_3_rows_2_columns

tensor([[ 1,  2],
        [ 6,  7],
        [11, 12]])

In [ ]:
# Task: Retrieve the rows and columns with odd-indexed positions from the tensor 'x'.
# Hint: Use stride slicing to extract the required subset of rows and columns with odd indices.
#cross - check this as you need to use stride.
odd_valued_rows_columns = x[::2,:][:,::2]
odd_valued_rows_columns

tensor([[ 1,  3,  5],
        [11, 13, 15]])

#  <font color = dodgerred>**Normalize Function**<font>

Writing the function that normalizes the columns of a matrix. We have to compute the mean and standard deviation of each column. Then for each element of the column, we subtract the mean and divide by the standard deviation.

In [ ]:
# Given Data
x = [[ 3,  60,  100, -100],
     [ 2,  20,  600, -600],
     [-5,  50,  900, -900]]

In [ ]:
# Convert to PyTorch Tensor and set to float
X = torch.tensor(x)
X= X.float()

In [ ]:
# Print shape and data type for verification
print(X.shape)
print(X.dtype)

torch.Size([3, 4])
torch.float32


In [ ]:
# Compute and display the mean and standard deviation of each column for reference
X.mean(axis = 0)
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

In [ ]:
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

- Your task starts here
- Your normalize_matrix function should take a PyTorch tensor x as input.
- It should return a tensor where the columns are normalized.
- After implementing your function, use the code provided to verify if the mean for each column in Z is close to zero and the standard deviation is 1.

In [ ]:
def normalize_matrix(x):
  # Calculate the mean along each column (think carefully , you will take mean along axis = 0 or 1)
  mean = x.mean(dim=0)

  # Calculate the standard deviation along each column
  std = x.std(dim=0)

  # Normalize each element in the columns by subtracting the mean and dividing by the standard deviation
  y = (x - mean) / std

  return y  # Return the normalized matrix



In [ ]:
Z = normalize_matrix(X)
Z

tensor([[ 0.6882,  0.8006, -1.0722,  1.0722],
        [ 0.4588, -1.1209,  0.1650, -0.1650],
        [-1.1471,  0.3203,  0.9073, -0.9073]])

In [ ]:
Z.mean(axis = 0)

tensor([ 0.0000e+00,  4.9671e-08,  3.9736e-08, -3.9736e-08])

# <font color = 'dodgerred'>**In-place vs. Out-of-place Operations**

1. Creating a tensor `A` with values `[1, 2, 3]`.
2. Performing an in-place addition (use `add_` method) of `5` to tensor `A`.
3. Then, creating another tensor `B` with values `[4, 5, 6]` and performing an out-of-place addition of `5`.

**Printing the memory addresses of `A` and `B` before and after the operations to demonstrate the difference in memory usage. Provided explanation**


In [ ]:
A = torch.tensor([1, 2, 3])
print('Original memory address of A:', id(A))
A.add_(5)
print('Memory address of A after in-place addition:', id(A))
print('A after in-place addition:', A)

B = torch.tensor([4, 5, 6])
print('Original memory address of B:', id(B))
B = B+5
print('Memory address of B after out-of-place addition:', id(B))
print('B after out-of-place addition:', B)


Original memory address of A: 135053321588384
Memory address of A after in-place addition: 135053321588384
A after in-place addition: tensor([6, 7, 8])
Original memory address of B: 135053322011248
Memory address of B after out-of-place addition: 135053322011648
B after out-of-place addition: tensor([ 9, 10, 11])


**Provide Explanation for above question here :**



Inplace operations updates the tensor A whereever its stored like in the same memory location hence memory efficient, whereas in Outplace operations the tesnor B stores the added value to the new memory location and B points to that memory location.

# <font color = 'dodgerred'>**Tensor Broadcasting**

1. Creating two tensors `X` with shape `(3, 1)` and `Y` with shape `(1, 3)`. Performing an addition operation on `X` and `Y`.
2. Explaining how broadcasting is applied in this operation by describing the shape changes that occur internally.

In [ ]:
X = torch.tensor([[100],
                  [200],
                  [300]])
Y = torch.tensor([[100,200,300]])
print('Original shapes:', X.shape, Y.shape)
result = X + Y
print('Result:', result)
print('Result shape:', result.shape)


Original shapes: torch.Size([3, 1]) torch.Size([1, 3])
Result: tensor([[200, 300, 400],
        [300, 400, 500],
        [400, 500, 600]])
Result shape: torch.Size([3, 3])


**Provide Explanation for above question here :**



Broadcasting is an effective way of performing operations on unequal sizes. As we can above we have unequal sizes X expands itself to the size (3, 3) by duplicating the columns and Y expands itself to the size (3, 3) by duplicating rows and then performs the addition.

# <font color = 'dodgerred'>**Linear Algebra Operations**

1. Creating two matrices `M1` and `M2` of compatible shapes for matrix multiplication. Perform the multiplication and print the result.
2. Then, creating two vectors `V1` and `V2` and computing their dot product.


In [ ]:
M1 = torch.arange(0,6).reshape(3,2)
M2 = torch.arange(0,6).reshape(2,3)
mat_multiplication =  torch.mm(M1,M2)
print('Matrix multiplication result:', mat_multiplication)

V1 = torch.tensor([1,1,1,1])
V2 = torch.tensor([2,2,2,2])
dot_product =  torch.dot(V1,V2)
print('Dot product:', dot_product)


Matrix multiplication result: tensor([[ 3,  4,  5],
        [ 9, 14, 19],
        [15, 24, 33]])
Dot product: tensor(8)


# <font color = 'dodgerred'>**Manipulating Tensor Shapes**

Given a tensor `T` with shape `(2, 3, 4)`, demonstrating how to
1. reshape it to `(3, 8)` using view,
2. reshape it to `(4, 2, 3` using reshape,
3. transpose the first and last dimensions using permute.
4. explaining what is the difference between reshape and view

In [ ]:
T = torch.rand(2, 3, 4)
T_view =  T.view(3,8)
print('T_view shape:', T_view.shape)

T_reshape =  T.reshape(4, 2, 3)
print('T_reshape shape:', T_reshape.shape)

T_permute =  T.permute(2,1,0)
print('T_permute shape:', T_permute.shape)

T_view shape: torch.Size([3, 8])
T_reshape shape: torch.Size([4, 2, 3])
T_permute shape: torch.Size([4, 3, 2])


**Provide Explanation for above question here :**



The difference is that View will not create a copy where as reshape may or may not share the same memory.
Another difference is that reshape can operate on both contiguous and non-contiguous tensors where view can operate only on contiguous tensor.

# <font color = 'dodgerred'>**Tensor Concatenation and Stacking**

Creating tensors `C1` and `C2` both with shape (2, 3).
1. Concatenating them along dimension 0 and then along dimension 1. Print the shape of the resulting tensor.
2. Afterwards, stacking the same tensors alomng dimension 0  and print the shape of the resulting tensor.
3. Explaining the difference between stacking and concatinating.

In [ ]:
C1 = torch.rand(2, 3)
C2 = torch.rand(2, 3)
concatenated_dim0 =  torch.cat((C1, C2),dim=0)
print('Concatenated along dimension 0:', concatenated_dim0.shape)

concatenated_dim1 =  torch.cat((C1, C2),dim=1)
print('Concatenated along dimension 1:', concatenated_dim1.shape)

stacked =  torch.stack((C1, C2),dim=0)
print('Stacked tensor shape:', stacked.shape)


Concatenated along dimension 0: torch.Size([4, 3])
Concatenated along dimension 1: torch.Size([2, 6])
Stacked tensor shape: torch.Size([2, 2, 3])


**The difference between concatinating and stacking here**




Concatinating joins the two tensors based on the dimension where as stacking adds a new dimension to the tensor.

# <font color = 'dodgerred'>**Advanced Indexing and Slicing**

1. Given a tensor `D` with shape (6, 6), extract elements that are greater than 0.5.
2. Then, extracting the second and fourth rows from `D`.
3. Finally, extracting a sub-tensor from the top-left 3x3 block.

In [ ]:
D = torch.rand(6, 6)
print('Elements greater than 0.5:\n', D[D > 0.5])

second_fourth_rows =  D[[1,3],:]
print('\nSecond and fourth rows:\n', second_fourth_rows)

top_left_3x3 =  D[:3, :3]
print('\nTop-left 3x3 block:\n ', top_left_3x3)


Elements greater than 0.5:
 tensor([0.5341, 0.8094, 0.9938, 0.6413, 0.8671, 0.5028, 0.9993, 0.7405, 0.6552,
        0.7448, 0.9404, 0.6635, 0.6203, 0.7955, 0.8076, 0.8135, 0.8934, 0.9192])

Second and fourth rows:
 tensor([[0.6413, 0.8671, 0.4113, 0.2380, 0.5028, 0.0139],
        [0.6552, 0.2813, 0.7448, 0.9404, 0.3760, 0.6635]])

Top-left 3x3 block:
  tensor([[0.5341, 0.2441, 0.8094],
        [0.6413, 0.8671, 0.4113],
        [0.3410, 0.3583, 0.2377]])


# <font color = 'dodgerred'>**Tensor Mathematical Operations (1 Point)**

1. Creating a tensor `G` with values from 0 to π in steps of π/4.
2. Computing and print the sine, cosine, and tangent logarithm and the exponential of `G`.

In [ ]:
import math
G = torch.arange(0, math.pi, step = math.pi/4)
print('G:', G)
print('Sine of G:',  torch.sin(G))
print('Cosine of G:',  torch.cos(G))
print('Tangent of G:',  torch.tan(G))
print('Natural logarithm of G:',  torch.log(G))
print('Exponential of G:',  torch.exp(G))


G: tensor([0.0000, 0.7854, 1.5708, 2.3562])
Sine of G: tensor([0.0000, 0.7071, 1.0000, 0.7071])
Cosine of G: tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01])
Tangent of G: tensor([ 0.0000e+00,  1.0000e+00, -2.2877e+07, -1.0000e+00])
Natural logarithm of G: tensor([   -inf, -0.2416,  0.4516,  0.8570])
Exponential of G: tensor([ 1.0000,  2.1933,  4.8105, 10.5507])


# <font color = 'dodgerred'>**Tensor Reduction Operations**

1. Creating a 3x2 tensor `H`.
2. Computing the sum of `H`. Printing the result and shape after taking sun.
3. Then, performing the same operations along dimension 0 and dimension 1, printing the results and shapes.
4. What do we observe, here? How the shape changes?

In [ ]:
H = torch.rand(3, 2)
print('H:', H, end = "\n\n")
print('Shape of original Tensor H', H.shape, end = "\n\n")

print('Sum of H:',  H.sum())
print('Shape after Sum of H:',  H.sum().shape,  end = "\n\n")

print('Sum of H along dimension 0:',  H.sum(dim=0))
print('Shape after sum of H along dimension 0:',  H.sum(dim=0).shape,  end = "\n\n")

print('Sum of H along dimension 1:', H.sum(dim=1))
print('Shape after sum of H along dimension 1:',  H.sum(dim=1).shape)


H: tensor([[0.5330, 0.9584],
        [0.0304, 0.4065],
        [0.3425, 0.8572]])

Shape of original Tensor H torch.Size([3, 2])

Sum of H: tensor(3.1281)
Shape after Sum of H: torch.Size([])

Sum of H along dimension 0: tensor([0.9060, 2.2221])
Shape after sum of H along dimension 0: torch.Size([2])

Sum of H along dimension 1: tensor([1.4915, 0.4369, 1.1997])
Shape after sum of H along dimension 1: torch.Size([3])


**Provide your observations on shape changes here**



Whem sum operation is performed on the entire tensor the shape of it is an empty tuple, where as if sum is performed along a specific dimension the shape gives remaining dimension.

# <font color = 'dodgerred'>**Working with Tensor Data Types**

1. Creating a tensor `I` of data type float with values `[1.0, 2.0, 3.0]`.
2. Converting `I` to data type int and print the result.
3. Explaining in which scenarios it's necessary to be cautious about the data type of tensors.

In [ ]:
# Solution for Q16
I =  torch.tensor([1.,2.,3.])
print('I:', I)
I_int =  I.int()
print('I converted to int:', I_int)

I: tensor([1., 2., 3.])
I converted to int: tensor([1, 2, 3], dtype=torch.int32)


**The explanations here**



Its necessary to be cautious about data types in tensor because specific operations may expect tensors to be in a specific data types and to avoid errors and memory allocation issues.

# <font color = 'dodgerred'>**Speedtest for vectorization** </font>

Our goal is to measure the speed of linear algebra operations for different levels of vectorization.

1. Constructing two matrices $A$ and $B$ with Gaussian random entries of size $1024 \times 1024$.
1. Computing $C = A B$ using matrix-matrix operations and report the time. (Hint: Use torch.mm)
1. Computing $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time. (hint use torch.mv inside a for loop)
1. Computing $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time. (Hint: use torch.dot inside nested for loop)

In [ ]:
## Solution 1
torch.manual_seed(42) # dod not chnage this
A = torch.randn(1024, 1024)
B = torch.randn(1024, 1024)

In [ ]:
## Solution 2
start=time.time()

C = torch.mm(A,B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.12469339370727539 seconds


In [ ]:
## Solution 3
C= torch.empty(1024,1024)
start = time.time()

for i in range(1024):
  C[:,i] = torch.mv(A, B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 4.09546160697937 seconds


In [ ]:
## Solution 4
C= torch.empty(1024,1024)
start = time.time()

for i in range(1024):
  for j in range(1024):
    C[i,j] = torch.dot(A[i,:],B[:,j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 33.110047578811646 seconds


# <font color = 'dodgerred'>**Redoing above by using GPU**

<font size = 4, color = 'dodgerred'> **Using GPUs**

How to we use GPUs in Google Colab<br>
In Google Colab -- Go to Runtime Tab at top -- select change runtime type -- for hardware accelartor choose GPU

In [ ]:
# Check if GPU is availaible
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [ ]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024),device=device)
B= torch.randn((1024, 1024),device=device)

In [ ]:
## Solution 2
start=time.time()

C = torch.mm(A,B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.1188042163848877 seconds


In [ ]:
## Solution 3
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(1024):
  C[:,i] = torch.mv(A, B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.11161017417907715 seconds


In [ ]:
## Solution 4
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(1024):
  for j in range(1024):
    C[i,j] = torch.dot(A[i,:],B[:,j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 42.43140411376953 seconds
